repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: mixed-line-ending
        args:
        -   --fix=lf
    -   id: check-added-large-files
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.6
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
        -   mdformat-black
